language: java
sudo: true
dist: trusty
jdk: oraclejdk8
before_install:
  - chmod +x mvnw

script:
  - cd /home/travis/build/AnushaKallem/DemoProject/target
  - java -jar DemoProject-0.0.1-SNAPSHOT.jar com.example.demo.DemoProjectApplication
	
cache:
  directories:
    - node_modules